### ISSUE TITLE
[BUG]: workers using PCIe instead of NVLink on the same node

### ISSUE THREAD

**Issue by 2018x5zzt** [ai-dynamo/dynamo#1072]
### Describe the Bug

I use Nsight System to monitor the transmission bandwidth utilization of a single request.(curl localhost) However, the bandwidth utilization of NVLink between the two workers is 0. It is speculated that PCIe may be used for transmission, because the bandwidth utilization of PCIe is not 0 at this time.

### Steps to Reproduce

# yaml：

```
Common:
  model: /models/Llama-3.1-8b-Instruct
  block-size: 64
  max-model-len: 3500
  router: kv
  kv-transfer-config: '{"kv_connector":"DynamoNixlConnector"}'

Frontend:
  served_model_name: Llama-3.1-8b-Instruct
  endpoint: dynamo.Processor.chat/completions
  port: 8000

Processor:
  common-configs: [model, block-size, max-model-len, router]

Router:
  min-workers: 1
  common-configs: [model]

VllmWorker:
  # max-num-batched-tokens: 3500
  remote-prefill: true
  conditional-disagg: false
  tensor-parallel-size: 1
  enable-prefix-caching: true
  ServiceArgs:
    workers: 1
    resources:
      gpu: 1
  common-configs: [model, block-size, max-model-len, router, kv-transfer-config]

PrefillWorker:
  max-num-batched-tokens: 3500
  gpu-memory-utilization: 0.98
  tensor-parallel-size: 1
  ServiceArgs:
    workers: 1
    resources:
      gpu: 1
  common-configs: [model, block-size, max-model-len, kv-transfer-config]
```

# my profile command：

`nsys profile --gpu-metrics-devices all --trace cuda,nvtx -o nsys_nixl_sys_new_70b -f true dynamo serve graphs.disagg_router:Frontend -f configs/disagg_router.yaml`

### Expected Behavior

The bandwidth utilization of the NVLink between two workers is not 0

### Actual Behavior

In addition, I was surprised that I observed NVLink transmission behavior when using Llama3.1-8b-Instruct for benchmark testing.

### Environment

Installation method: container/build.sh
ai-dynamo version: 0.2.0
Operating System : Ubuntu 24.04
Docker Version : 28.0.4

### Screenshots

<img width="763" alt="Image" src="https://github.com/user-attachments/assets/7f59442f-92f6-44e8-8378-8f352ae2dbc4" />

The lower one is the prefill node, the upper one is the decode node. The bandwidth utilization of the nvlink in the middle is 0

![Image](https://github.com/user-attachments/assets/2442d2db-7e23-49ca-b848-6dc3c401745f)

However, in the 3.1-8b benchmark test, I unexpectedly saw that the bandwidth utilization of nvlink was not 0.
