### ISSUE TITLE
[BUG]: SGLang Connection closed by peer

### ISSUE THREAD

**Issue by YosanHo** [ai-dynamo/dynamo#1148]
### Describe the Bug

SGLangDecodeWorker dead with Connection closed by peer using 2 * 8H20

### Steps to Reproduce

1. first node startup Frontend and SGLangWorker

    disagg.yaml

    ```yaml
    Frontend:
      served_model_name: DeepSeek-R1
      model-path: /data/DeepSeek-R1
      endpoint: dynamo.SGLangWorker.generate
    
    # We set disaggregation-bootstrap-port in utils/sglang.py to ensure unique ports for each replica
    SGLangWorker:
      model-path:  /data/DeepSeek-R1
      served-model-name: DeepSeek-R1
      tp: 8
      host: xxxxxx
      mem-fraction-static: 0.91
      trust-remote-code: true
      skip-tokenizer-init: true
      disaggregation-mode: prefill
      disaggregation-transfer-backend: nixl
      ServiceArgs:
        workers: 1
        resources:
          gpu: 8
    ```
    
    start command
    
    ```shell
    dynamo serve graphs.disagg:Frontend \
    -f /dynamo/examples/sglang/configs/disagg.yaml \
    --working-dir /dynamo/examples/sglang \
    -p 8080 --host xxxxx
    ```
2. second node startup SGLangDecodeWorker

    disagg.yaml

    ```yaml
    SGLangDecodeWorker:
      model-path: /data/DeepSeek-R1
      served-model-name: DeepSeek-R1
      tp: 8
      host: xxxxxxx
      mem-fraction-static: 0.91
      trust-remote-code: true
      skip-tokenizer-init: true
      disaggregation-mode: decode
      disaggregation-transfer-backend: nixl
      ServiceArgs:
        workers: 1
        resources:
          gpu: 8
    ```
    
    start command
    
    ```shell
    dynamo serve graphs.disagg:SGLangDecodeWorker \
    -f /dynamo/examples/sglang/configs/disagg.yaml \
    --working-dir /dynamo/examples/sglang \
    -p 8080 --host xxxxx
    ```

### Expected Behavior

run well

### Actual Behavior

with sglang benchmark uitls, occur error

```
python -m sglang.bench_serving --backend vllm --dataset-name random-ids --model DeepSeek-R1 \
--output-file online.jsonl --host xxxxx --port 8080 \
--model /dataDeepSeek-R1 \
--random-input 512 --random-output 512 --random-range-ratio 1 --num-prompts 1000 \
--request-rate 3 --max-concurrency 55
```

### Environment

```
ystem Information:
OS: AlmaLinux 9.2
Glibc Version: 2.34
GCC Version: 11.3.1-4)
Cmake Version: 3.20.2
Rust Version: N/A
Docker Version: N/A

CPU Information:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Address sizes:                   46 bits physical, 57 bits virtual
Byte Order:                      Little Endian
CPU(s):                          212
On-line CPU(s) list:             0-211
Vendor ID:                       GenuineIntel
Model name:                      Intel(R) Xeon(R) Platinum 8480+
CPU family:                      6
Model:                           143
Thread(s) per core:              2
Core(s) per socket:              53
Socket(s):                       2
Stepping:                        8
BogoMIPS:                        4000.00
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology cpuid tsc_known_freq pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch cpuid_fault invpcid_single ssbd ibrs ibpb stibp ibrs_enhanced fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid avx512f avx512dq rdseed adx smap avx512ifma clflushopt clwb avx512cd sha_ni avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves avx_vnni avx512_bf16 wbnoinvd arat avx512vbmi umip pku ospke waitpkg avx512_vbmi2 gfni vaes vpclmulqdq avx512_vnni avx512_bitalg avx512_vpopcntdq rdpid cldemote movdiri movdir64b fsrm md_clear serialize tsxldtrk arch_lbr amx_bf16 avx512_fp16 amx_tile amx_int8 arch_capabilities
Hypervisor vendor:               KVM
Virtualization type:             full
L1d cache:                       5 MiB (106 instances)
L1i cache:                       3.3 MiB (106 instances)
L2 cache:                        212 MiB (106 instances)
L3 cache:                        210 MiB (2 instances)
NUMA node(s):                    2
NUMA node0 CPU(s):               0-105
NUMA node1 CPU(s):               106-211
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Not affected
Vulnerability Retbleed:          Not affected
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Enhanced IBRS, IBPB conditional, RSB filling
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Mitigation; TSX disabled

Python Version: 3.12.9
Python Platform: Linux-5.10.135-6-velinux1u1-amd64-x86_64-with-glibc2.34

Python Packages:
ai-dynamo: 0.2.1
ai-dynamo-runtime: 0.2.1
ai-dynamo-vllm: Not installed
genai-perf: Not installed
nixl: 0.2.1
numpy: 2.2.6
nvidia-cublas-cu12: 12.4.5.8
nvidia-cuda-cupti-cu12: 12.4.127
nvidia-cuda-nvrtc-cu12: 12.4.127
nvidia-cuda-runtime-cu12: 12.4.127
nvidia-cudnn-cu12: 9.1.0.70
nvidia-cufft-cu12: 11.2.1.3
nvidia-curand-cu12: 10.3.5.147
nvidia-cusolver-cu12: 11.6.1.9
nvidia-cusparse-cu12: 12.3.1.170
nvidia-ml-py: 12.570.86
nvidia-nccl-cu12: 2.21.5
nvidia-nvjitlink-cu12: 12.4.127
nvidia-nvtx-cu12: 12.4.127
pyzmq: 26.4.0
tensorrt_llm: Not installed
torch: 2.6.0
torchaudio: 2.6.0
transformers: 4.51.1
tritonclient: Not installed
```
