### ISSUE TITLE
[BUG]:  PD disaggregation performance & CUDAGraph abnormal

### ISSUE THREAD

**Issue by IEI-mjx** [ai-dynamo/dynamo#1369]
### Describe the Bug

After testing qwq_32b_bf16 in PD disagg case and nonPD disagg case, we found some unexpected data.
Here are the conclusion of my issues:
1.Cudagraph in Vllmworker will lead to higher TTFT
2.The total throughput is not changed when add more D
3.Why TTFT in PD case is higher than nonPD case when concurrency < 4 and lower when concurrency > 8?

### Steps to Reproduce

Here is my yaml file in PD disagg case:

```
Common:
  model: Qwen/QwQ-32B
  kv-transfer-config: '{"kv_connector":"DynamoNixlConnector"}'
  router: round-robin
  # Number of tokens in a batch for more efficient chunked transfers to GPUs.
  block-size: 16
  max-model-len: 32768
  max-num-batched-tokens: 32768
  disable-log-requests: true
  enable-prefix-caching: false
  enforce-eager: true

Frontend:
  # This model was chosen for its 70B size and FP8 precision, which the TP and
  # DP configurations were tuned for its size, and its precision reduces model
  # and KV cache memory usage and easing remote cache transfer.
  served_model_name: Qwen/QwQ-32B
  endpoint: dynamo.Processor.chat/completions
  port: 9000

Router:
  common-configs: [model]
  min-workers: 1


Processor:
  common-configs: [model, router, block-size]

# x1 process with 4 GPUs generating output tokens (the "decode" phase).
VllmWorker:
  common-configs: [model, kv-transfer-config, router, block-size, max-model-len, disable-log-requests, enable-prefix-caching, enforce-eager]
  # Enable prefill at different workers.
  remote-prefill: true
  # Disable local prefill so only disaggregated prefill is used.
  conditional-disagg: false
  gpu-memory-utilization: 0.95
  tensor-parallel-size: 2
  ServiceArgs:
    workers: 1
    resources:
      gpu: 2

# x4 processes each with 1 GPU handling the initial prefill (context embedding) phase.
PrefillWorker:
  common-configs: [model, kv-transfer-config, block-size, max-model-len, max-num-batched-tokens, gpu-memory-utilization, disable-log-requests, enable-prefix-caching, enforce-eager]
  tensor-parallel-size: 2
  ServiceArgs:
    workers: 1
    resources:
      gpu: 2

```

Here is yaml in NonPD case:
```
Common:
  model: Qwen/QwQ-32B
  block-size: 16
  max-model-len: 32768
  enable-prefix-caching: false

Frontend:
  served_model_name: Qwen/QwQ-32B
  endpoint: dynamo.Processor.chat/completions
  port: 9000

Processor:
  router: round-robin
  common-configs: [model, block-size, max-model-len]

VllmWorker:
  enforce-eager: true
  max-num-batched-tokens: 32768
  router: random
  gpu-memory-utilization: 0.95
  tensor-parallel-size: 2
  ServiceArgs:
    workers: 1
    resources:
      gpu: 2
  common-configs: [model, block-size, max-model-len, enable-prefix-caching]
```
Here is the start command:
1.PD case: dynamo serve benchmarks.disagg:Frontend -f ./benchmarks/disagg_qwen_qwq.yaml
2.nonPD: dynamo serve graphs.agg:Frontend -f ./configs/agg.yaml

We test benchmarks using `perf.sh`

### Expected Behavior

We started all dynamo servers based on the `README` you provided.
But the results (shown below) were out of our expectation.

### Actual Behavior

Here is our benchmark results:
<html xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=PowerPoint.Slide>
<meta name=Generator content="Microsoft PowerPoint 15">
<style>

</style>
</head>

<body>

Case ID | PD比例 | 节点数 | tp_size | TTFT avg / s | 吞吐 tokens / s | 并发大小
-- | -- | -- | -- | -- | -- | --
CASE-001 | 1:1 | 1 | Ptp2/Dtp2 | 1.64/1.84/2.09/2.58/3.34 | 32/63/121/228/394 | 1/2/4/8/16
CASE-002 | 1:1 | 1 | Ptp4/Dtp4 | 0.98/1.13/1.25/1.57/2.33 | 32/64/124/240/449 | 1/2/4/8/16
CASE-003 | 1:2 | 1 | Ptp2/Dtp2 *2 | 2.49/1.82/2.39/2.89/4.11 | 32/65/125/239/428 | 1/2/4/8/16
CASE-004 | 1:3 | 1 | Ptp2/Dtp2 *3 | 1.60/1.95/2.26/2.77/4.6 | 32/64/125/240/428 | 1/2/4/8/16
CASE-005 | 2:2 | 1 | Ptp2 *2/Dtp2 * 2 | 1.68/1.66/1.92/2.29/2.81 | 32/65/129/243/447 | 1/2/4/8/16
CASE-006 | 1:1 | 1 | Ptp2/Dtp4 | 1.65/1.67/1.90/2.13/2.60 | 32/63/124/237/451 | 1/2/4/8/16

</body>

</html>

<html xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=PowerPoint.Slide>
<meta name=Generator content="Microsoft PowerPoint 15">
<style>

</style>
</head>

<body>

Case ID | PD比例 | 节点数 | tp_size | TTFT avg / s | 吞吐 tokens / s | 并发大小
-- | -- | -- | -- | -- | -- | --
开启eager | 1:1 | 1 | Ptp4/Dtp4 | 0.98/1.13/1.25/1.57/2.33 | 32/64/124/240/449 | 1/2/4/8/16
默认eager配置 | 1:1 | 1 | Ptp4/Dtp4 | 0.92/3.17/3.95/5.49/24.1 | 57/97/179/305/337 | 1/2/4/8/16
PD均关闭eager | 1:1 | 1 | Ptp4/Dtp4 | 0.97/3.43/4.18/5.95/26.8 | 57/96/176/293/319 | 1/2/4/8/16

</body>

</html>

### Environment

dynamo 0.1.0
vllm 0.7.2+dynamo patch
model qwq_32b_bf16
