### ISSUE TITLE
gRPC OutOfRange Error  AND  CUDA Out of Memory Error

### ISSUE THREAD

**Issue by Alan-D-Chen** [ai-dynamo/dynamo#1534]
### Describe the Bug

@dzier Hello, thank you for your attention and help! Firstly, I have updated to the latest Dynamo version, Dynamo CLI version: 0.3.0, and perhaps the original issue has been resolved in this version. However, in the latest Dynamo version, Dynamo CLI version: 0.3.0, a more critical point is that using the same YAML file and test startup command has led to a new, potentially more serious issue.

In decode node, we run Dynamo with this yaml : 
```
Frontend:
  served_model_name: Qwen3-32B
  endpoint: dynamo.Processor.chat/completions
  port: 9000

Processor:
  model: /mnt/LLM_models/Qwen3-32B
  block-size: 64
  max-model-len: 6144
  router: kv

Router:
  model: /mnt/LLM_models/Qwen3-32B
  min-workers: 1

VllmWorker:
  model: /mnt/LLM_models/Qwen3-32B
  kv-transfer-config: '{"kv_connector":"DynamoNixlConnector"}'
  block-size: 64
  max-model-len: 6144
  max-num-seqs: 64
  remote-prefill: true
  conditional-disagg: false
  max-local-prefill-length: 20
  max-prefill-queue-size: 32
  gpu-memory-utilization: 0.90
  tensor-parallel-size: 4
  router: kv
  enable-prefix-caching: false
  ServiceArgs:
    workers: 1
    resources:
      gpu: 4

PrefillWorker:
  model: /mnt/LLM_models/Qwen3-32B
  kv-transfer-config: '{"kv_connector":"DynamoNixlConnector"}'
  block-size: 64
  max-model-len: 6144
  max-num-seqs: 64
  gpu-memory-utilization: 0.90
  tensor-parallel-size: 4
  ServiceArgs:
    workers: 2
    resources:
      gpu: 4
```

In decode node, **dynamo 0.3.0**, but got these errors:

1. gRPC OutOfRange Error
Error Message:
plaintext
grpc request error: status: OutOfRange, message: "Error, decoded message length too large: found 16265467 bytes, the limit is: 4194304 bytes"

> Root Cause(maybe):
> The gRPC request to retrieve components from etcd exceeded the default message size limit (4MB), with the actual message size being ~16MB.
> The dynamo namespace in etcd contained excessive metadata, causing large response payloads when fetching components with kv_get_prefix.

2. CUDA Out of Memory Error
Error Message:
plaintext
torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 126.00 MiB. GPU has < 100MiB free.

> Root Cause(maybe):
> Loading the 32B-parameter Qwen3 model without quantization required excessive GPU memory:
> FP32 precision requires ~128GB VRAM, but only 4x47GB GPUs were available.
> Inadequate model parallelism configuration (tensor_parallel_size=4) failed to sufficiently distribute memory load across GPUs.

(BUT in **dynamo 0.1.1**, with Qwen3-32B it is okay, the vllm benchmark is working, and we got these final testing results)

For more information in decode node, please go to the error_decode.txt  => 

[error_decode.txt](https://github.com/user-attachments/files/20746150/error_decode.txt)

For more information in prefill node, please go to the prefill.txt  => 

[prefill.txt](https://github.com/user-attachments/files/20746155/prefill.txt)

### Steps to Reproduce

And the modifications I made, BUT these fixings didn't work.

In decode node, 
```
docker exec -it dynamo_alanchenx /bin/bash -c \
    "cd /workspace/examples/llm && \
    export DYNAMO_GRPC_MAX_MESSAGE_SIZE=104857600 && \
    dynamo serve graphs.agg_router:Frontend \
    -f ./configs/multinode-Qwen3-32B_tp2.yaml \
    --port 4500"
```

In prefill node,
```
docker exec -it "$CONTAINER_NAME" /bin/bash -c "
    export NATS_SERVER='nats://10.66.6.70:4222'
    export ETCD_ENDPOINTS='http://10.66.6.70:2379'
    export DYNAMO_GRPC_MAX_MESSAGE_SIZE=104857600 && \
    cd /workspace/examples/llm
    dynamo serve components.prefill_worker:PrefillWorker -f ./configs/multinode-Qwen3-32B_tp2.yaml --port 4500
"
```

### Expected Behavior

The vllm benchmark will work, and wewill get these final testing results

### Actual Behavior

The dynamo do not work

### Environment

root@5468a701:/workspace# dynamo --version
Dynamo CLI version: 0.3.
