### ISSUE TITLE
Error results in Dynamo + vLLM framework for inference testing of DeepSeek-R1-Distill-Llama-70B with PD Disaggregated Deployment

### ISSUE THREAD

**Issue by Alan-D-Chen** [ai-dynamo/dynamo#1593]
### Describe the Bug

When using the Dynamo + vLLM framework for inference testing of DeepSeek-R1-Distill-Llama-70B with PD Disaggregated Deployment, an anomaly occurs. The joint framework performs well in the early stage of the test, but in the later stage, the progress bar moves forward rapidly and reaches 100% within a short period (see the pic 1). In the Serving Benchmark Result, multiple metrics show zero values, which is clearly abnormal(see the pic 2).

![Image](https://github.com/user-attachments/assets/f867e96a-1341-4aa0-97e7-d5080d827e23)

![Image](https://github.com/user-attachments/assets/1bb5912a-6b68-459f-8320-090bcf9c3ed2)

error results, like this:

![Image](https://github.com/user-attachments/assets/5b5122ae-ddad-4ccb-b547-976f420f906c)

We set the yaml file, like this:

```
Frontend:
  served_model_name: DeepSeek-R1-Distill-Llama-70B
  endpoint: dynamo.Processor.chat/completions
  port: 9000

Processor:
  model: /mnt/LLM_models/DeepSeek-R1-Distill-Llama-70B
  block-size: 64
  max-model-len: 6144
  router: kv

Router:
  model: /mnt/LLM_models/DeepSeek-R1-Distill-Llama-70B
  min-workers: 1

VllmWorker:
  model: /mnt/LLM_models/DeepSeek-R1-Distill-Llama-70B
  kv-transfer-config: '{"kv_connector":"DynamoNixlConnector"}'
  block-size: 64
  max-model-len: 6144
  max-num-seqs: 256
  remote-prefill: true
  conditional-disagg: false
  max-local-prefill-length: 10
  max-prefill-queue-size: 4
  gpu-memory-utilization: 0.95
  tensor-parallel-size: 8
  router: kv
  enable-prefix-caching: false
  ServiceArgs:
    workers: 1
    resources:
      gpu: 8

PrefillWorker:
  model: /mnt/LLM_models/DeepSeek-R1-Distill-Llama-70B
  kv-transfer-config: '{"kv_connector":"DynamoNixlConnector"}'
  block-size: 64
  max-model-len: 6144
  max-num-seqs: 256
  gpu-memory-utilization: 0.95
  tensor-parallel-size: 4
  ServiceArgs:
    workers: 2
    resources:
      gpu: 4
```

### Steps to Reproduce

dynamo + vllm set like :  https://github.com/ai-dynamo/dynamo/issues/1534  and  https://github.com/ai-dynamo/dynamo/issues/1471

### Expected Behavior

vllm  inference testing

### Actual Behavior

error result

### Environment

dynamo 0.3.0 
dynamo + vllm set like :  https://github.com/ai-dynamo/dynamo/issues/1534  and  https://github.com/ai-dynamo/dynamo/issues/1471
