### ISSUE TITLE
[BUG]: failed to join writer task: I/O error: Broken pipe (os error 32)

### ISSUE THREAD

**Issue by jifa513** [ai-dynamo/dynamo#1594]
### Describe the Bug

When I run the Sao10K/L3-8B-Stheno-v3.2 model with dynamo-0.2.1, with agg_router.yaml, it produces errors : 

````
[2m2025-06-18T11:18:35.326Z[0m [32m INFO[0m [2mengine._handle_process_request[0m[2m:[0m Added request 353523e8-431d-45b6-879d-fb545e3bfa3b.   
[2m2025-06-18T11:18:35.706Z[0m [31mERROR[0m [2mdynamo_runtime::pipeline::network::tcp::client[0m[2m:[0m failed to join writer task: I/O error: Broken pipe (os error 32)

Caused by:
    Broken pipe (os error 32)
[2m2025-06-18T11:18:35.714Z[0m [31mERROR[0m [2mdynamo_runtime::pipeline::network::ingress::push_handler[0m[2m:[0m Failed to publish response for stream 6dc5234b-d582-425d-9127-585b0877c96d
[2m2025-06-18T11:18:35.736Z[0m [31mERROR[0m [2m_core[0m[2m:[0m Failed to send response: SendError { .. }
[2m2025-06-18T11:18:35.736Z[0m [31mERROR[0m [2mdynamo_runtime::pipeline::network::tcp::client[0m[2m:[0m failed to join writer task: I/O error: Broken pipe (os error 32)

Caused by:
    Broken pipe (os error 32)
[2m2025-06-18T11:18:35.744Z[0m [31mERROR[0m [2mdynamo_runtime::pipeline::network::ingress::push_handler[0m[2m:[0m Failed to publish response for stream 0074571c-1642-415d-a105-c8d118877c13
[2m2025-06-18T11:18:35.766Z[0m [32m INFO[0m [2mengine._handle_abort_request[0m[2m:[0m Aborted request 353523e8-431d-45b6-879d-fb545e3bfa3b.
````

anyone know how to solve this problem ??

### Steps to Reproduce

1. deploy etcd and nats with the command `docker compose -f deploy/metrics/docker-compose.yml up -d`;
2. launch the docker container with dynamo docker image;
3. In the docker container, modify the /workspace/examples/llm/configs/agg_router.yaml as:
`
```
Common:
  model: /models/hub/models--Sao10K--L3-8B-Stheno-v3.2/snapshots/4bb828f6e1b1efd648c39b1ad682c44ff260f018
  router: kv
  block-size: 64
  max-model-len: 8192
  kv-transfer-config: '{"kv_connector":"DynamoNixlConnector"}'

  Frontend:
    served_model_name: Sao10K/L3-8B-Stheno-v3.2
    endpoint: dynamo.Processor.chat/completions
    port: 8000
   
  Processor:
    common-configs: [model, block-size, max-model-len, router]

  Router:
    min-workers: 1
    common-configs: [model, router]

  VllmWorker:
    max-num-batched-tokens: 16384
    enable-prefix-caching: true
    tensor-parallel-size: 1
  ServiceArgs:
    workers: 4
    resources:
      gpu: 1
  common-configs: [model, block-size, max-model-len, router, kv-transfer-config]
```
`
4. dynamo serve graphs.agg_router:Frontend -f ./configs/agg_router.yaml;

and when processing some of the requests, dynamo will launch the error:
````
[2m2025-06-18T11:18:35.326Z[0m [32m INFO[0m [2mengine._handle_process_request[0m[2m:[0m Added request 353523e8-431d-45b6-879d-fb545e3bfa3b.   
[2m2025-06-18T11:18:35.706Z[0m [31mERROR[0m [2mdynamo_runtime::pipeline::network::tcp::client[0m[2m:[0m failed to join writer task: I/O error: Broken pipe (os error 32)

Caused by:
    Broken pipe (os error 32)
[2m2025-06-18T11:18:35.714Z[0m [31mERROR[0m [2mdynamo_runtime::pipeline::network::ingress::push_handler[0m[2m:[0m Failed to publish response for stream 6dc5234b-d582-425d-9127-585b0877c96d
[2m2025-06-18T11:18:35.736Z[0m [31mERROR[0m [2m_core[0m[2m:[0m Failed to send response: SendError { .. }
[2m2025-06-18T11:18:35.736Z[0m [31mERROR[0m [2mdynamo_runtime::pipeline::network::tcp::client[0m[2m:[0m failed to join writer task: I/O error: Broken pipe (os error 32)

Caused by:
    Broken pipe (os error 32)
[2m2025-06-18T11:18:35.744Z[0m [31mERROR[0m [2mdynamo_runtime::pipeline::network::ingress::push_handler[0m[2m:[0m Failed to publish response for stream 0074571c-1642-415d-a105-c8d118877c13
[2m2025-06-18T11:18:35.766Z[0m [32m INFO[0m [2mengine._handle_abort_request[0m[2m:[0m Aborted request 353523e8-431d-45b6-879d-fb545e3bfa3b.
````

### Expected Behavior

How to solve this problem?

### Actual Behavior

some of requests cause the 'failed to join writer task: I/O error: Broken pipe (os error 32)' error in dynamo

### Environment

Linux host-10-200-1-2 5.15.0-141-generic #151-Ubuntu SMP Sun May 18 21:35:19 UTC 2025 x86_64 x86_64 x86_64 GNU/Linux
dynamo-v0.2.1
GPU:  8 * h100
CPU:
processor       : 191
vendor_id       : GenuineIntel
cpu family      : 6
model           : 143
model name      : Intel(R) Xeon(R) Platinum 8468
stepping        : 8
microcode       : 0x2b000639
cpu MHz         : 2101.000
cache size      : 107520 KB
physical id     : 1
siblings        : 96
core id         : 47
cpu cores       : 48
apicid          : 223
initial apicid  : 223
fpu             : yes
fpu_exception   : yes
cpuid level     : 32
wp              : yes
