### ISSUE TITLE
[BUG]: DecoderWorker hang 5min and timeout in multinodes PD disaggregation case

### ISSUE THREAD

**Issue by IEI-mjx** [ai-dynamo/dynamo#1607]
### Describe the Bug

DecodeWorker hang when using qwq32b model, 2 nodes 1P1D tp_size=8

### Steps to Reproduce

Here is qwq32b.yaml
```
Common:
  model: /mnt/maojunxiong/models--Qwen--QwQ-32B/snapshots/976055f8c83f394f35dbd3ab09a285a984907bd0/
  kv-transfer-config: '{"kv_connector":"NixlConnector","kv_role":"kv_both"}'
  served_model_name: Qwen/QwQ-32B
  tensor-parallel-size: 8

Frontend:
  endpoint: dynamo.SimpleLoadBalancer.generate_disagg
  port: 9000
  served_model_name: Qwen/QwQ-32B

SimpleLoadBalancer:
  enable_disagg: true
  common-configs: [model, kv-transfer-config, served_model_name]

VllmPrefillWorker:
  enforce-eager: true
  ServiceArgs:
    workers: 1
    resources:
      gpu: '8'
  common-configs: [model, kv-transfer-config, served_model_name, tensor-parallel-size]

VllmDecodeWorker:
  enforce-eager: true
  ServiceArgs:
    workers: 1
    resources:
      gpu: '8'
  common-configs: [model, kv-transfer-config, served_model_name, tensor-parallel-size]
```
Here is the steps: 
1.start etcd/nats server and export host & ports  
2.start ray 
3.node1:dynamo serve graphs.agg:Frontend -f configs/qwq_32b.yaml
4.node2: dynamo serve components.worker:VllmPrefillWorker -f configs/qwq_32b.yaml
5.bash perf.sh

### Expected Behavior

In one node 1P1D tp_size=4 the results are normal.
In two nodes 1P1D tp_size=8 the DecodeWorker stucked.

### Actual Behavior

![Image](https://github.com/user-attachments/assets/0c196ddd-1583-4c07-b494-6f376f631ae9)

### Environment

dynamo 0.3.0 + vllm_0.9.1_v1 build on Dockerfile.vllm_v1 for WideEP

### Additional Context

In addition, when tested WideEP we encountered the above error:

![Image](https://github.com/user-attachments/assets/c9509264-1248-4721-93d1-d82853369908)

We couldn't find the right host and port !!
