### ISSUE TITLE
can not load model from local dir?

### ISSUE THREAD

**Issue by Lzhang-hub** [ai-dynamo/dynamo#280]
agg.yaml

```
Frontend:
  model: /data/models/hf/Qwen/Qwen2.5-7B-Instruct
  endpoint: dynamo.Processor.chat/completions
  port: 8000

Processor:
  model: /data/models/hf/Qwen/Qwen2.5-7B-Instruct
  block-size: 64
  max-model-len: 16384
  router: round-robin

VllmWorker:
  model: /data/models/hf/Qwen/Qwen2.5-7B-Instruct
  enforce-eager: true
  block-size: 64
  max-model-len: 16384
  max-num-batched-tokens: 16384
  enable-prefix-caching: true
  router: random
  tensor-parallel-size: 1
  served-model-name: "qwen"
  ServiceArgs:
    workers: 1
```

got error:
```
chat model /data/models/hf/Qwen/Qwen2.5-7B-Instruct removed from the public namespace: public
2025-03-19T04:14:12.396642Z ERROR dynamo_runtime::worker: Application shutdown with error: Model name '/data/models/hf/Qwen/Qwen2.5-7B-Instruct' cannot start with a slash
Error: Model name '/data/models/hf/Qwen/Qwen2.5-7B-Instruct' cannot start with a slash
```

**Comment by dmitry-tokarev-nv** [comment]
@Lzhang-hub Thank you for your report. Can you share your platform details (OS version, CPU arch, Python version) and how you installed Dynamo?

**Comment by Lzhang-hub** [comment]
@dmitry-tokarev-nv 
I run in docker image `nvcr.io/nvidia/cuda:12.5.1-devel-ubuntu24.04` wirh python 3.12, amd64.

I think it might be releated the code [model_name start with '/'](https://github.com/ai-dynamo/dynamo/blob/372511d77ed0c7f13d3f8f092dd972088a2e95f1/launch/llmctl/src/main.rs#L231)

**Comment by ayrnb** [comment]
+1

**Comment by ptarasiewiczNV** [comment]
The `.Frontend.model` is really just a name that will be served on the chat/completions endpoint. On the other hand `. VllmWorker.model` is the checkpoint name/path.

Could you please try:
```
Frontend:
  model: my_model_name
  endpoint: dynamo.Processor.chat/completions
  port: 8000

Processor:
  model: /data/models/hf/Qwen/Qwen2.5-7B-Instruct
  block-size: 64
  max-model-len: 16384
  router: round-robin

VllmWorker:
  model: /data/models/hf/Qwen/Qwen2.5-7B-Instruct
  enforce-eager: true
  block-size: 64
  max-model-len: 16384
  max-num-batched-tokens: 16384
  enable-prefix-caching: true
  router: random
  tensor-parallel-size: 1
  served-model-name: "qwen"
  ServiceArgs:
    workers: 1
```

@ishandhanani What do you think about changing the `Frontend` parameter to `served_model_name`? This would follow vllm convention, where `model` is the checkpoint and `served_model_name` is used in the endpoint.

**Comment by piotrm-nvidia** [comment]
The ``processor`` model name here should be related to tokenizer used there? Should we change this to tokenizer and also consider model_or_checkpoint for worker? 

Model seems to be confusing here.

**Comment by ishandhanani** [comment]
@ptarasiewiczNV - yep this is a good idea. I can see how that can be confusing. Let me run a test with that config that you provided above (local model) and I'll put up a PR

**Comment by ishandhanani** [comment]
> The `processor` model name here should be related to tokenizer used there? Should we change this to tokenizer and also consider model_or_checkpoint for worker?
> 
> Model seems to be confusing here.

We might have to do some mapping in the component logic for this. Right now we have `model` in processor because that's directly turned into an `engine_arg` for VLLM to parse.

**Comment by ishandhanani** [comment]
Hi @Lzhang-hub - I was able to confirm that @ptarasiewiczNV was right. Check this out

local-model-agg.yaml
```
Frontend:
  served_model_name: Qwen/Qwen2.5-7B-Instruct
  endpoint: dynamo.Processor.chat/completions
  port: 8000

Processor:
  model: /workspace/qwenmodel
  block-size: 64
  max-model-len: 16384
  router: round-robin

VllmWorker:
  model: /workspace/qwenmodel
  enforce-eager: true
  block-size: 64
  max-model-len: 16384
  max-num-batched-tokens: 16384
  enable-prefix-caching: true
  router: random
  tensor-parallel-size: 1
  served-model-name: "qwen"
  ServiceArgs:
    workers: 1
```

```
root@machine:/workspace/qwenmodel# ll
total 14885612
drwxr-xr-x 3 root root       4096 Mar 19 20:11 ./
drwxr-xr-x 1 root root       4096 Mar 19 20:11 ../
drwxr-xr-x 3 root root       4096 Mar 19 20:11 .cache/
-rw-r--r-- 1 root root       1519 Mar 19 20:11 .gitattributes
-rw-r--r-- 1 root root      11343 Mar 19 20:11 LICENSE
-rw-r--r-- 1 root root       6240 Mar 19 20:11 README.md
-rw-r--r-- 1 root root        663 Mar 19 20:11 config.json
-rw-r--r-- 1 root root        243 Mar 19 20:11 generation_config.json
-rw-r--r-- 1 root root    1671839 Mar 19 20:11 merges.txt
-rw-r--r-- 1 root root 3945441440 Mar 19 20:11 model-00001-of-00004.safetensors
-rw-r--r-- 1 root root 3864726352 Mar 19 20:11 model-00002-of-00004.safetensors
-rw-r--r-- 1 root root 3864726424 Mar 19 20:11 model-00003-of-00004.safetensors
-rw-r--r-- 1 root root 3556377672 Mar 19 20:11 model-00004-of-00004.safetensors
-rw-r--r-- 1 root root      27752 Mar 19 20:11 model.safetensors.index.json
-rw-r--r-- 1 root root    7031645 Mar 19 20:11 tokenizer.json
-rw-r--r-- 1 root root       7305 Mar 19 20:11 tokenizer_config.json
-rw-r--r-- 1 root root    2776833 Mar 19 20:11 vocab.json
```

```
curl localhost:8000/v1/chat/completions   -H "Content-Type: application/json"   -d '{
    "model": "Qwen/Qwen2.5-7B-Instruct",
    "messages": [
    {
        "role": "user",
        "content": "Tell me about the absolute legend Roger Federer"
    }
    ],
    "stream":false,
    "max_tokens": 30
  }'

{"id":"0c32da16-a44d-4b22-bd5a-79feee2ef5a7","choices":[{"index":0,"message":{"content":"Roger Federer is widely regarded as one of the greatest tennis players of all time, known for his exceptional talent, grace, and sportsmanship both on","refusal":null,"tool_calls":null,"role":"assistant","function_call":null,"audio":null},"finish_reason":"length","logprobs":null}],"created":1742416690,"model":"Qwen/Qwen2.5-7B-Instruct","service_tier":null,"system_fingerprint":null,"object":"chat.completion","usage":null}
```
