### ISSUE TITLE
How to run PD disaggregating server on multiple nodes?

### ISSUE THREAD

**Issue by yangsijia-serena** [ai-dynamo/dynamo#291]
Hi, could you please give an example of running PD disaggregating on multiple nodes using `dynamo serve`? 
I set the disagg.yaml as
```
Frontend:
  model: /data00/models/xxx
  endpoint: dynamo.Processor.chat/completions
  port: 8000

Processor:
  model: /data00/models/xxx
  router: round-robin

VllmWorker:
  # vllm enging args
  model: /data00/models/xxx
  kv-transfer-config: '{"kv_connector":"DynamoNixlConnector"}'
  max-model-len: 16384
  tensor-parallel-size: 8

  # dynamo args
  remote-prefill: true
  conditional-disagg: true
  max-local-prefill-length: 10
  ServiceArgs:
    workers: 1
    resources:
      gpu: 8

PrefillWorker:
  # vllm enging args
  model: /data00/models/xxx
  kv-transfer-config: '{"kv_connector":"DynamoNixlConnector"}'
  max-model-len: 16384
  max-num-batched-tokens: 16384
  tensor-parallel-size: 8
  ServiceArgs:
    workers: 1
    resources:
      gpu: 8
```
I want to run VllmWorker and PrefillWorker separately on two nodes, each with 8 GPUs. However, it seems that both workers are attempting to run on a single node, resulting in a `Current node has no GPU available` error.

Any suggestions or guides would be appreciated, thanks a lot!

**Comment by arunraman** [comment]
Add the etcd and nats environment variables to the workers under `ServiceArgs` in the yaml . Replace the `nats_server` and `etcs_server` with its corresponding IP.  

```
    envs:
      NATS_SERVER: nats://<nats_server>:4222
      ETCD_ENDPOINTS: http://<etcs_server>:2379
```


example on node 1, you can do 

```
Frontend:
  model: /data00/models/xxx
  endpoint: dynamo.Processor.chat/completions
  port: 8000

Processor:
  model: /data00/models/xxx
  router: round-robin

VllmWorker:
  # vllm enging args
  model: /data00/models/xxx
  kv-transfer-config: '{"kv_connector":"DynamoNixlConnector"}'
  max-model-len: 16384
  tensor-parallel-size: 8
  # dynamo args
  remote-prefill: true
  conditional-disagg: true
  max-local-prefill-length: 10
  ServiceArgs:
    workers: 1
    resources:
      gpu: 8
    envs:
      NATS_SERVER: nats://<nats_server>:4222
      ETCD_ENDPOINTS: http://<etcs_server>:2379

PrefillWorker:
  # vllm engine args
  model: /data00/models/xxx
  kv-transfer-config: '{"kv_connector":"DynamoNixlConnector"}'
  max-model-len: 16384
  max-num-batched-tokens: 16384
  tensor-parallel-size: 8
  ServiceArgs:
    workers: 1
    resources:
      gpu: 8
    envs:
      NATS_SERVER: nats://<nats_server>:4222
      ETCD_ENDPOINTS: http://<etcs_server>:2379
```

on the second node where you want to deploy the second decoder

```
VllmWorker:
  # vllm enging args
  model: /data00/models/xxx
  kv-transfer-config: '{"kv_connector":"DynamoNixlConnector"}'
  max-model-len: 16384
  tensor-parallel-size: 8
  # dynamo args
  remote-prefill: true
  conditional-disagg: true
  max-local-prefill-length: 10
  ServiceArgs:
    workers: 1
    resources:
      gpu: 8
    envs:
      NATS_SERVER: nats://<nats_server>:4222
      ETCD_ENDPOINTS: http://<etcs_server>:2379
```

This will register the second worker to the namespace in the etcd.
