### ISSUE TITLE
Distributed Runtime I/O error

### ISSUE THREAD

**Issue by ayrnb** [ai-dynamo/dynamo#357]
When i increase the length of the output, the following error occurs:

![Image](https://github.com/user-attachments/assets/8d099f72-4661-4b52-916b-faa150365561)

**Comment by ayrnb** [comment]
The client log shows that when the output is 1500 and num_requset is 32 , some generated tokens are lost.

![Image](https://github.com/user-attachments/assets/5b20284b-0d72-4002-a053-d62498bbef3b)

**Comment by dmitry-tokarev-nv** [comment]
@ayrnb can you provide more details on how to reproduce this issue?

1. What does your env look like?
2. OS version, CPU arch, GPU hardware. 
3. Are you running in a VM, container, bare metal?
4. How did you install Dynamo - with pip install?
5. What exact commands are you executing?

**Comment by ayrnb** [comment]
@dmitry-tokarev-nv 
os：Ubuntu22.04  8*H20；
running in container；
command：ETCD_ENDPOINTS=192.168.12.11:2379 NATS_SERVER=nats://192.168.12.11:4222 \
dynamo serve graphs.agg:Frontend -f ./configs/agg_qwq.yaml

```
configs/agg_qwq.yaml
Frontend:
  model: Qwen/QwQ-32B
  endpoint: dynamo.Processor.chat/completions
  port: 8000

Processor:
  model: /data/models/QwQ-32B/
  block-size: 64
  max-model-len: 32768
  router: round-robin

VllmWorker:
  # vllm enging args
  model: /data/models/QwQ-32B
  kv-transfer-config: '{"kv_connector":"DynamoNixlConnector"}'
  block-size: 64
  enable-chunked-prefill: true
  max-model-len: 32768 # 
  max-num-batched-tokens: 131072
  tensor-parallel-size: 2 # 
  enforce-eager: false 
  # dynamo args
  remote-prefill: false
  conditional-disagg: false
  max-local-prefill-length: 10 # remote prefill最低 prompt tokens
  ServiceArgs:
    workers: 1  
    resources:
      gpu: 2 

benchmark_serving.py command

 python3 /root/vllm/benchmarks/benchmark_serving.py \
            --backend openai-chat  \
            --model /data/models/QwQ-32B \
            --base-url http://127.0.0.1:8000 \
            --endpoint /v1/chat/completions \
            --num-prompts $PROMPTS \
            --request-rate $RATE \
            --profile \
            --metric_percentiles '50,90,95,99' \
            --goodput ttft:5000 tpot:250 \
            --max-concurrency $CONCURRENCY \
            --random-input-len $INPUT_LEN \
            --random-output-len $OUTPUT_LEN \
            --dataset-name random \
            --ignore-eos --trust-remote-code \
            --save-result \
            --served-model-name Qwen/QwQ-32B

**Comment by ayrnb** [comment]
With lower QPS, there are fewer errors

**Comment by ishandhanani** [comment]
Hey @ayrnb - we have made a lot of updates to dynamo and this has not come up in our load tests. Could you try to rebuild off of main and try again? Also - can you share your env vars for the benchmarking script? I don't have access to 8xH20 but am trying to repro on 8xA100-80GB. Steps are below

---

I build a container off of main 974201c869d883f6f8ca8f716f743844fab6951a

I run the aggregated example using your YAML. I made some updates as our spec changed since this issue. Full YAML is below

```yaml
Frontend:
  served_model_name: Qwen/QwQ-32B
  endpoint: dynamo.Processor.chat/completions
  port: 8000

Processor:
  model: Qwen/QwQ-32B
  block-size: 64
  max-model-len: 32768
  router: round-robin

VllmWorker:
  model: Qwen/QwQ-32B
  kv-transfer-config: '{"kv_connector":"DynamoNixlConnector"}'
  block-size: 64
  enable-chunked-prefill: true
  max-model-len: 32768 #
  max-num-batched-tokens: 131072
  tensor-parallel-size: 2 #
  enforce-eager: false
  remote-prefill: false
  conditional-disagg: false
  max-local-prefill-length: 10
  ServiceArgs:
    workers: 1
    resources:
      gpu: 2
```

I run this with

```bash
dynamo serve graphs.agg:Frontend -f ./configs/test_qwq.yaml
```

I am able to get through the load test without any errors. Again note I am not using all of configurations as I do not know all of your env vars

```
python3 benchmark_serving.py \
            --backend openai-chat  \
            --model Qwen/QwQ-32B \
            --base-url http://localhost:8000 \
            --endpoint /v1/chat/completions \
            --profile \
            --metric_percentiles '50,90,95,99' \
            --goodput ttft:5000 tpot:250 \
            --max-concurrency 32 \
            --random-output-len 1500 \
            --dataset-name random \
            --ignore-eos --trust-remote-code \
            --save-result \
            --served-model-name Qwen/QwQ-32B
```

Let me know
