### ISSUE TITLE
Llama 70B 2 Node Example

### ISSUE THREAD

**Issue by liao4s** [ai-dynamo/dynamo#362]
Can you give a more detailed configuration of this experiment? For example, how many prefillworkers are included in a one node experiment, how much parallelism is set for each PrefillWorker, how many Gpus are a single PrefillWorker, and what are the VllmWorker? What is the configuration for two nodes?

![Image](https://github.com/user-attachments/assets/5f0a7190-987f-463a-957b-e263f1bf4b39)

**Comment by kkranen** [comment]
Hey there @liao4s.

This example was run with 2 H100 DGX Nodes in the same cluster.

The configurations were:

Prefill - 2xTP4
Decode - 1xTP8

We hope to publish this example soon.

**Comment by liao4s** [comment]
Thanks for your reply, can you give the detailed content of yaml file used in this experiment?

**Comment by liwei-rk** [comment]
what's the x-axis meaning for "tokens/s/user" ? how can we setup the same input to test this scenario ?

**Comment by liao4s** [comment]
> what's the x-axis meaning for "tokens/s/user" ? how can we setup the same input to test this scenario ?

Have you successfully run the two-node PD disaggregated serving experiment mentioned above(Prefill - 2xTP4,Decode - 1xTP8)?

**Comment by kkranen** [comment]
We're working on providing an example that does exactly this. The original experiment wasn't run using the YAML flow, so we are currently porting it. 

Tok/s/usr is single stream tok/s in a concurrent environment.

Renaming to indicate that the task is for example creation.

**Comment by liao4s** [comment]
> We're working on providing an example that does exactly this. The original experiment wasn't run using the YAML flow, so we are currently porting it.
> 
> Tok/s/usr is single stream tok/s in a concurrent environment.
> 
> Renaming to indicate that the task is for example creation.

Thanks for your reply. Is the single-node experiment conducted through a YAML file? If is, can you show the contents of YAML?

**Comment by liao4s** [comment]
> ey there [@liao4s](https://github.com/liao4s).  嘿 。
> 
> This example was run with 2 H100 DGX Nodes in the same cluster.此示例在同一集群中使用 2 个 H100 DGX 节点运行。
> 
> The configurations were:  配置如下：
> 
> Prefill - 2xTP4  预填充 - 2xTP4 Decode - 1xTP8  解码 - 1xTP8
> 
> We hope to publish this example soon.我们希望很快发布这个例子。

Hi, thank you very much for your recent update. I have successfully run the 2-node experiment through yaml startup service, but the experiment results are very different from the expectation. I would like to ask you the specific parameters of the 2-node experiment at that time. For example, block-size, max-model-len, max-num-batched-tokens, conditional-disagg, max-local-prefill-length, What does max-prefill-queue-size, tensor-parallel-size, router, enable-prefix-caching correspond to respectively? And how are the other parameters set? My own yaml file is as follows:
prefill_worker.yaml:
```
PrefillWorker:
  model: /models/hub/DeepSeek-R1-Distill-Llama-70B-FP8-dynamic
  kv-transfer-config: '{"kv_connector":"DynamoNixlConnector"}'
  block-size: 64
  max-model-len: 16384
  max-num-batched-tokens: 16384
  tensor-parallel-size: 4
  ServiceArgs:
    workers: 2
    resources:
      gpu: 4
```
disagg_router.yaml:
```
Frontend:
  served_model_name: DeepSeek-R1-Distill-Llama-70B-FP8-dynamic
  endpoint: dynamo.Processor.chat/completions
  port: 8000

Processor:
  model: /models/hub/models--neuralmagic--DeepSeek-R1-Distill-Llama-70B-FP8-dynamic
  block-size: 64
  max-model-len: 16384
  router: kv

Router:
  model-name: /models/hub/models--neuralmagic--DeepSeek-R1-Distill-Llama-70B-FP8-dynamic
  min-workers: 1

VllmWorker:
  model: /models/hub/models--neuralmagic--DeepSeek-R1-Distill-Llama-70B-FP8-dynamic
  kv-transfer-config: '{"kv_connector":"DynamoNixlConnector"}'
  block-size: 64
  max-model-len: 16384
  max-num-batched-tokens: 16384
  remote-prefill: true
  conditional-disagg: true
  max-local-prefill-length: 1000
  max-prefill-queue-size: 8
  tensor-parallel-size: 8
  router: kv
  enable-prefix-caching: true
  ServiceArgs:
    workers: 1
    resources:
      gpu: 8
```

And how are the parameters of your benchmark set? For example, what's request_rate? My benchmark parameters are set as follows:
```
pd_describe=${1:-"2node-2x4p-1x8d-remote"}
model=${2:-"DeepSeek-R1-Distill-Llama-70B-FP8-dynamic"}
random_output_len=${3:-"150"}
request_rate=${4:-"100"}
num_prompts=${5:-"500"}
random_input_len=${6:-"3000"}
python3 sglang_benchmark.py --backend vllm \
    --base-url http://localhost:8000 \
    --endpoint /v1/chat/completions \
    --dataset-name random \
    --model ${model} \
    --tokenizer /etc/nexus/proxy/net_proxy/hub/models--neuralmagic--DeepSeek-R1-Distill-Llama-70B-FP8-dynamic \
    --num-prompts ${num_prompts} --random-input-len ${random_input_len} --random-output-len ${random_output_len} --request-rate ${request_rate}\
    --output-file benchmark_log/${pd_describe}_n${num_prompts}_in${random_input_len}_out${random_output_len}_qps${request_rate}.json \
    --pd-seperated
```
