### ISSUE TITLE
Compared to SGLNG, Dynamo services have lower throughput. Is it a problem with my configuration?

### ISSUE THREAD

**Issue by a4zhangfei** [ai-dynamo/dynamo#387]
Our test results show that the concurrency is not high. Is there a problem with my configuration?
PrefillWorker handles a single request every time. Is it the problem here? How to change it to batch?
https://github.com/ai-dynamo/dynamo/blob/457e78fb759accc9a3e38f6afc1050b0a7b8ba91/examples/llm/components/prefill_worker.py#L103-L106

Dyname result: Request throughput is 1.10 (TP1 BF16 3P1D)
```
============ Serving Benchmark Result ============
Backend:                                 vllm
Traffic request rate:                    32.0
Max reqeuest concurrency:                not set
Successful requests:                     1000
Benchmark duration (s):                  907.39
Total input tokens:                      4007607
Total generated tokens:                  56814
Total generated tokens (retokenized):    50731
Request throughput (req/s):              1.10
Input token throughput (tok/s):          4416.63
Output token throughput (tok/s):         62.61
Total token throughput (tok/s):          4479.24
Concurrency:                             481.16
----------------End-to-End Latency----------------
Mean E2E Latency (ms):                   436601.67
Median E2E Latency (ms):                 440035.82
---------------Time to First Token----------------
Mean TTFT (ms):                          433931.46
Median TTFT (ms):                        437615.93
P99 TTFT (ms):                           865498.48
---------------Inter-Token Latency----------------
Mean ITL (ms):                           11.60
Median ITL (ms):                         11.52
P95 ITL (ms):                            12.52
P99 ITL (ms):                            13.84
Max ITL (ms):                            119.50
==================================================
```

sglang result: Request throughput is 6.42 (TP1 BF16 3P1D)
```
============ Serving Benchmark Result ============
Backend:                                 sglang
Traffic request rate:                    32.0
Max reqeuest concurrency:                not set
Successful requests:                     1000
Benchmark duration (s):                  155.80
Total input tokens:                      4007607
Total generated tokens:                  109354
Total generated tokens (retokenized):    76166
Request throughput (req/s):              6.42
Input token throughput (tok/s):          25723.23    8574.41 tok/s/gpu
Output token throughput (tok/s):         701.90
Total token throughput (tok/s):          26425.13
Concurrency:                             398.61
----------------End-to-End Latency----------------
Mean E2E Latency (ms):                   62102.68
Median E2E Latency (ms):                 62686.63
---------------Time to First Token----------------
Mean TTFT (ms):                          60663.67
Median TTFT (ms):                        61226.33
P99 TTFT (ms):                           120785.82
---------------Inter-Token Latency----------------
Mean ITL (ms):                           13.30
Median ITL (ms):                         12.51
P95 ITL (ms):                            15.42
P99 ITL (ms):                            29.09
Max ITL (ms):                            322.48
==================================================
```
graph config: 3 Prefill worker and 1 decode worker
```
Frontend:
  served_model_name: model-thought-7b
  endpoint: dynamo.Processor.chat/completions
  port: 8000
  ServiceArgs:
    workers: 4

Processor:
  model: /mnt/yscfs/model-thought/rag_fc_7b_20250314_Qwen25_7b_instruct_yuanshi_chat_v4_bf16_thought_action_250313/
  router: round-robin
  ServiceArgs:
    workers: 4

VllmWorker:
  model: /mnt/yscfs/model-thought/rag_fc_7b_20250314_Qwen25_7b_instruct_yuanshi_chat_v4_bf16_thought_action_250313/
  kv-transfer-config: '{"kv_connector":"DynamoNixlConnector"}'
  max-model-len: 16384
  remote-prefill: true
  conditional-disagg: true
  max-local-prefill-length: 10
  tensor-parallel-size: 1
  ServiceArgs:
    workers: 1
    resources:
      gpu: 1

PrefillWorker:
  model: /mnt/yscfs/model-thought/rag_fc_7b_20250314_Qwen25_7b_instruct_yuanshi_chat_v4_bf16_thought_action_250313/
  kv-transfer-config: '{"kv_connector":"DynamoNixlConnector"}'
  max-model-len: 16384
  max-num-batched-tokens: 16384
  tensor-parallel-size: 1
  ServiceArgs:
    workers: 3
    resources:
      gpu: 1

```

**Comment by liao4s** [comment]
嘿，你好，很抱歉我不知道怎么解决你所遇到的问题。但是有一个请求，想知道你的benchmark代码是自己编写的吗？还是开源的代码呢？可以分享一下这个benchmark所用到的代码吗？

**Comment by liao4s** [comment]
Hi, I'm sorry I don't know how to solve your problem. But I have a request. Is the benchmark you use written by yourself? Or open source code? Can you share this benchmark?

**Comment by a4zhangfei** [comment]
> Hi, I'm sorry I don't know how to solve your problem. But I have a request. Is the benchmark you use written by yourself? Or open source code? Can you share this benchmark?

@liao4s we based on SGLang's bench_serving：https://github.com/sgl-project/sglang/blob/main/python/sglang/bench_serving.py

**Comment by liao4s** [comment]
> > Hi, I'm sorry I don't know how to solve your problem. But I have a request. Is the benchmark you use written by yourself? Or open source code? Can you share this benchmark?
> 
> [@liao4s](https://github.com/liao4s) we based on SGLang's bench_serving：https://github.com/sgl-project/sglang/blob/main/python/sglang/bench_serving.py

Thank you so much！

**Comment by sitabulaixizawaluduo** [comment]
The disaggregate PD of sglang should not currently include kv cache transfer, so the throughput will be higher.

**Comment by a4zhangfei** [comment]
> The disaggregate PD of sglang should not currently include kv cache transfer, so the throughput will be higher.
@sitabulaixizawaluduo 

We have made modifications based on sglang and already support kv transmission. The above test feels very problematic and does not start concurrently.

**Comment by sitabulaixizawaluduo** [comment]
> > The disaggregate PD of sglang should not currently include kv cache transfer, so the throughput will be higher.
> > [@sitabulaixizawaluduo](https://github.com/sitabulaixizawaluduo)
> > We have made modifications based on sglang and already support kv transmission. The above test feels very problematic and does not start concurrently.

The results show that the TTFT of SGLang is smaller and the ITL is similar, indicating that the efficiency of KV Cache transfer is higher?

**Comment by liao4s** [comment]
> > Hi, I'm sorry I don't know how to solve your problem. But I have a request. Is the benchmark you use written by yourself? Or open source code? Can you share this benchmark?
> 
> [@liao4s](https://github.com/liao4s) we based on SGLang's bench_serving：https://github.com/sgl-project/sglang/blob/main/python/sglang/bench_serving.py

In this script, if vllm is backend, the API_URL used is /v1/completions. It seems that dynamo does not support this form now (someone mentioned it in the issue, as shown in the following figure). Can you tell me what changes you made?
```
elif args.backend in ["sglang-oai", "vllm", "lmdeploy"]:
        api_url = (
            f"{args.base_url}/v1/completions"
            if args.base_url
            else f"http://{args.host}:{args.port}/v1/completions"
        )
```

![Image](https://github.com/user-attachments/assets/5496629a-a684-4324-8990-bbc4648240ed)

**Comment by a4zhangfei** [comment]
> base_url

We changed some of the code to adapt to dynamo's request：
![Image](https://github.com/user-attachments/assets/d0ca1f6a-c794-41bf-86d3-ea7fd81217c0)

![Image](https://github.com/user-attachments/assets/9e12553d-793e-41a0-8929-238447630b41)

**Comment by liao4s** [comment]
> > base_url
> > We changed some of the code to adapt to dynamo's request：
> > ![Image](https://github.com/user-attachments/assets/d0ca1f6a-c794-41bf-86d3-ea7fd81217c0)
> 
> ![Image](https://github.com/user-attachments/assets/9e12553d-793e-41a0-8929-238447630b41)

Thanks! This benchmark is running successfully!

**Comment by kkranen** [comment]
Dynamo using VLLM should use inflight batching by default, so I'm not sure this is a batching issue.

As mentioned, ITLs look on the same order of magnitude, this seems like Prefill being an issue, the question is why.

Would you be able to send the logs showing the distribution of workers routed to for prefill? Should be round robin, but there could be a bug with worker stackup.

**Comment by gujingit** [comment]
@a4zhangfei Hi, how can I run SGLang with PD-disagg? It seems that SGLang does not currently support PD-disagg, as noted in sgl-project/sglang#4655.

**Comment by mjp9527** [comment]
```
parser.add_argument(
        "--max-prefill-queue-size",
        type=int,
        default=3,
        help="Do not send remote prefill requests (prefill locally) if the queue size is greater than this value",
    )
```
Maybe it's because this parameter wasn't set?  All the requests are using locally prefill .

**Comment by liao4s** [comment]
Maybe you didn't send enough requests? How about a few more tests? I ran the tests on 8xH100, each time I set it to 500 requests, and found that the results of the first test were significantly worse than the results of the second and third tests, and kept the vllm api_server running for multiple tests. I guess it's because the model needs to "warm up."

**Comment by a4zhangfei** [comment]
> Maybe you didn't send enough requests? How about a few more tests? I ran the tests on 8xH100, each time I set it to 500 requests, and found that the results of the first test were significantly worse than the results of the second and third tests, and kept the vllm api_server running for multiple tests. I guess it's because the model needs to "warm up."

I am the test after warmup.

**Comment by liao4s** [comment]
> > Maybe you didn't send enough requests? How about a few more tests? I ran the tests on 8xH100, each time I set it to 500 requests, and found that the results of the first test were significantly worse than the results of the second and third tests, and kept the vllm api_server running for multiple tests. I guess it's because the model needs to "warm up."
> 
> I am the test after warmup.

Well, I guess we'll just have to hope for the author's reply.

**Comment by liho00** [comment]
Hi ser how do you run dynamo with sglang, are you using ubuntu 22.02?

**Comment by piotrm-nvidia** [comment]
I will review your questions tomorrow.

See similar question about 70B model: https://github.com/ai-dynamo/dynamo/issues/402#issuecomment-2769181444

>Disaggregation can bring significant benefits in specific throughput ranges. Based on experiments, configurations that aim for roughly 30–60 tokens/sec per user often show better performance in a disaggregated setup than on a single aggregated node. Outside that range, traditional setups (aggregated) may outperform the disaggregated approach.
>
>As an example, consider a scenario that targets 38 tokens/sec per user with a 3000-token input and a 150-token output. Here, a disaggregated configuration can achieve around 1.6× performance improvement over an aggregated single-node approach (normalized for GPU count).

In many random benchmarking scenarios, an aggregated setup often delivers similar performance because a disaggregated configuration must be carefully tuned to a specific type of load. Only with this tuning you can see benefits. For example, if your users typically provide short inputs but require long outputs, you won’t see much benefit from disaggregation. The key is to ensure that your workload fits the ideal throughput range (e.g., 30–60 tokens/sec per user) where disaggregation has been shown to outperform a single aggregated node for your typical request (e.g. 3000 input tokens with 150 output tokens). Otherwise, the traditional aggregated approach may gave similar performance.

![dynamo](https://github.com/ai-dynamo/dynamo/blob/188c3ff2c8c4eb8073c7eebfccba45cb99403007/docs/images/disagg_perf_benefit.png?raw=true)

**Comment by piotrm-nvidia** [comment]
I noticed the YAML configurations from ticket 387 differ from those provided in ticket 402, and it's important we clarify these differences to achieve optimal performance.

First, regarding the 7B model you're working with, it naturally requires about ten times less KV cache than the 70B model. This significant reduction in KV cache means your compute requirements will be considerably smaller, so the current configuration might not be optimal if directly copied from the 70B example.

Additionally, the parameters like `conditional-disagg` and `max-local-prefill-length` haven't undergone extensive testing yet, especially for the 7B scenario. Keeping these settings identical to the 70B model might still yield decent results, but since this hasn't been extensively verified, some experimentation could be beneficial.

It's crucial to ensure your prefill configurations are accurate. Incorrect setups might result in only one GPU actively computing during the generation phase, drastically underutilizing your available hardware resources. This could explain potential discrepancies in performance results you've observed.

Are your total token outputs normalized according to GPU count? The deployment with Dynamo utilizes three prefill GPUs, each handling a single GPU, whereas sglang might be deployed differently, possibly using fewer GPUs. Ensuring consistency in GPU utilization across both setups will provide a clearer picture of actual performance.

Another critical aspect is the ratio between prefill and generate workers. Checking GPU utilization using a tool like `nvtop` could provide insights into whether this ratio significantly impacts your performance outcomes.

Regarding benchmarking, the tools you're currently using do not display detailed information on input length and expected output token count. This could skew your comparisons, especially if sglang tends to produce more verbose outputs than Dynamo. The benchmark used for the 70B model employs `genai-perf`, which generates synthetic workloads with fixed token counts. Although enforcing a constant generation of 150 tokens is not reflective of real-world scenarios, it helps clearly compare different configurations. It might be beneficial to test your setup with `genai-perf` as well.

Lastly, it’s unclear whether the load conditions for Dynamo and sglang are truly comparable. The reported concurrency for Dynamo was 481, while for sglang, it was 398. The `genai-perf` benchmark explicitly controls concurrency (for example, keeping 32 clients constantly sending requests), ensuring a consistent and comparable workload. Adjusting your benchmarks to mirror this method would help clarify performance comparisons. For Dynamo and vLLM setups, maintaining an equivalent perceived performance of 38 tokens per second per user has allowed for a fairer concurrency comparison. Aligning your sglang benchmarks similarly might be insightful.

While I can't promise specific outcomes, previous experiments with an 8B LLAMA model and disaggregation showed considerable performance improvements, especially when input lengths approached around 10,000 tokens for 150-token outputs. Testing with `genai-perf` can help you find the exact point where your configuration outperforms the traditional setup. To achieve accurate results, I strongly recommend beginning your experiments with configurations more closely aligned to the proven 70B model setup.

I can also share draft of YAML configuration for 7B model:


```yaml
Frontend:
  served_model_name: example-7B
  endpoint: dynamo.Processor.chat/completions
  port: 8000

Processor:
  model: /path/to/my_7b_model/
  router: round-robin

VllmWorker:
  model: /path/to/my_7b_model/
  kv-transfer-config: '{"kv_connector":"DynamoNixlConnector"}'
  remote-prefill: true
  tensor-parallel-size: 2    # For generation more TP is better because less memory is used by model and more by KV cache
  block-size: 128 # Default is 64 and 128 is better for 70B model. You need to experiment with this value.
  # Potentially more config...
  ServiceArgs:
    workers: 1
    resources:
      gpu: 2

PrefillWorker:
  model: /path/to/my_7b_model/
  kv-transfer-config: '{"kv_connector":"DynamoNixlConnector"}'
  max-model-len: 16384
  block-size: 128
  tensor-parallel-size: 1
  # Potentially more config...
  ServiceArgs:
    workers: 3 # Is this amount of workers matches ratio between KV cache generation and token generation?
    resources:
      gpu: 1
```

**Notes**: 
- Here, 2 GPUs handle token generation (the decode phase), and each Prefill worker has 1 GPU. 
- Adjust `tensor-parallel-size` to match your model and GPU count. 
- Test different concurrency levels and measure throughput using a consistent tool like `genai-perf`.


**Further Reading & References**:

- [Dynamo LLM Examples](https://github.com/ai-dynamo/dynamo/tree/main/examples/llm)  
- [genai-perf for Synthetic LLM Load Testing](https://docs.nvidia.com/deeplearning/triton-inference-server/user-guide/docs/perf_analyzer/genai-perf/README.html)
