### ISSUE TITLE
How to configure it so that each worker exclusively uses one GPU?

### ISSUE THREAD

**Issue by alexngng** [ai-dynamo/dynamo#390]
While using Dynamo, I set the number of workers in VllmWorker to 3, expecting it to load three separate weight files and occupy 3 GPUs. However, it seems that all of them are squeezed onto the first GPU, causing the startup OOM e to faill.
```
Frontend:
  model: models/llama3.1-8b-ins/
  endpoint: dynamo.Processor.chat/completions
  port: 8000

Processor:
  model: models/llama3.1-8b-ins/
  router: round-robin

VllmWorker:
  # vllm enging args
  model: models/llama3.1-8b-ins/
  kv-transfer-config: '{"kv_connector":"DynamoNixlConnector"}'
  max-model-len: 16384
  gpu-memory-utilization: 0.85
  # dynamo args
  remote-prefill: true
  conditional-disagg: true
  max-local-prefill-length: 10
  tensor-parallel-size: 1
  ServiceArgs:
    workers: 3
    resources:
      gpu: 3

PrefillWorker:
  # vllm enging args
  model: models/llama3.1-8b-ins/
  kv-transfer-config: '{"kv_connector":"DynamoNixlConnector"}'
  max-model-len: 16384
  gpu-memory-utilization: 0.85
  # dynamo arg for local deployment
  cuda-visible-device-offset: 3
```

**Comment by kkranen** [comment]
I believe the config above may be stacking up contexts on all 3 of your gpus, can you rerun with ```gpu: 1```?

This probably needs to be documented better, but the gpus in resources are per instance.

**Comment by hutm** [comment]
```
  ServiceArgs:
    workers: 3
    resources:
      gpu: 1
```
should fix it. `gpu` property defines number of GPUs per worker.
