### ISSUE TITLE
How to support heterogeneous chips?

### ISSUE THREAD

**Issue by skyCreateXian** [ai-dynamo/dynamo#414]
As shown in the theme, I want to use 4090 as a prefix and L20 as a worker. How should I do it

**Comment by piotrm-nvidia** [comment]
Please see [example of disaggregated serving](https://github.com/ai-dynamo/dynamo/tree/main/examples/llm#disaggregated-serving). There is also guide about [dynamo serve](https://github.com/ai-dynamo/dynamo/blob/main/docs/guides/dynamo_serve.md).


In a disaggregated architecture, the **prefill worker** handles the initial token computation (“prefill”), while the **decode worker** handles the remaining tokens and the final generation steps. This lets you scale or dedicate different GPUs to each stage as needed.

1. **Prefill Worker (4090)** – Handles the heavy lifting of initial token embedding and KV cache creation.  
2. **Decode Worker (L20)** – Receives partially filled KV caches and continues with the decode/generation phase.

You can see the reference code in:
- [examples/llm/graphs/disagg.py](https://github.com/ai-dynamo/dynamo/blob/main/examples/llm/configs/disagg.yaml)
- [examples/llm/configs/disagg.yaml](https://github.com/ai-dynamo/dynamo/blob/main/examples/llm/configs/disagg.py)

These show how the **Frontend** → **Processor** → **VllmWorker** → **PrefillWorker** chain is set up. By default, `disagg.yaml` is configured for a single machine using GPU=0 for first worker, and GPU=1 for second worker.


## Understanding YAML Configuration

In the `disagg.yaml` example, each worker has a `ServiceArgs` section like this:

```yaml
VllmWorker:
  ...
  ServiceArgs:
    workers: 1  # Number of workers used
    resources:
      gpu: 1    # Number of GPUs used

PrefillWorker:
  ...
  ServiceArgs:
    workers: 1  # Number of workers used
    resources:
      gpu: 1    # Number of GPUs used
```

### Steps to Use Different GPUs

1. **Identify GPU indices**  
   - On a single machine, use `nvidia-smi` or a similar tool to see which GPU is index 0 (the 4090) and which is index 1 (the L20).  
   - If the 4090 is GPU=0 and the L20 is GPU=1, then this configuration example will work for you.

2. **Confirm VRAM Requirements**  
   - Make sure each GPU has enough memory for its stage of the pipeline. Typically, prefill can also be memory-intensive because it loads the model.

4. **Start the Deployment**  
   - Run (from within the examples directory ``examples/llm``):
     ```bash
     dynamo serve graphs.disagg:Frontend -f ./configs/disagg.yaml
     ```
   - Observe logs to confirm that each worker is properly assigned to its corresponding GPU and that everything is connected.

5. **Send Test Requests**  
   - You can use `curl` or your client library to send a test request to the frontend on port 8000.  
   - Check that the pipeline successfully executes prefill on the 4090 and decode on the L20.


## Questions to Consider

- **Single Machine or Multiple Machines?**  
  - If both GPUs are on the same machine single execution of dynamo serve is simple.  
  - If on separate machines, you’ll need to ensure they are connected via NATS/etcd, and your `kv-transfer-config` is properly pointing them to the same KV store.

- **Do You Have NVLink?**  
  - NVLink provides faster GPU-to-GPU communication compared to PCIe. If your GPUs share a fast interconnect, you might see better performance with high concurrency. You need to check [NIXL](https://github.com/ai-dynamo/nixl) support matrix to see what types of connections between GPUs are supported. 

- **Concurrency and Scaling**  
  - Disaggregation allows you to scale each phase independently. For example, if prefill quickly becomes a bottleneck, you could launch additional PrefillWorker processes (on more GPUs) while reusing a smaller number of decode workers.

- **Model Size and Context Length**  
  - Check that your chosen GPU for each step can store the model weights plus any KV caches (especially for large context windows like 16k tokens or more). If your L20 has lower VRAM, watch out for out-of-memory errors during the decode phase.

**Comment by skyCreateXian** [comment]
Thank you for providing the solution. I will try it out immediately

**Comment by skyCreateXian** [comment]
@piotrm-nvidia 
1、I know how to set up NATS and etcd,
export ETCD_ENDPOINTS=http://x:2379
export NATS_SERVER=nats://x:4222
but I'm not sure how to configure the kv store. Do you have any relevant documentation?
2、I plan to use L20 as node1 and 4090 as node2
Can you provide some explanations of YAML configuration for multi node deployment

**Comment by harryskim** [comment]
Asked our team member to provide heterogenous HW support guide. He will paste the link soon

**Comment by Ethan-ES** [comment]
## Multi-Node Deployment Guide

Assume there are two nodes, A and B, with the following roles:

1. **Node A (Head Node):** Frontend + Processor + VllmWorker  
2. **Node B (Prefill Worker Node):** PrefillWorker  

### Deployment Steps

1. **Start ETCD and NATS.io on Node A**  
```bash
   docker compose -f deploy/docker-compose.yml up -d
````

2. **Launch the Container Image on Both Nodes**

   ```bash
   bash ./container/run.sh --framework VLLM -it \
     -v "$(pwd)":/workspace/dynamo \
     -v "path_to_model":/workspace/model/Llama-3.1-8B-Instruct
   ```

3. **Edit the Configuration File**
   For example, using the local Llama-3.1-8B-Instruct model:

   ```yaml
   # configs/multinode_pd.yaml

   Common:
     model: /workspace/model/Llama-3.1-8B-Instruct
     block-size: 64
     max-model-len: 16384
     router: kv
     kv-transfer-config: '{"kv_connector":"DynamoNixlConnector"}'

   Frontend:
     served_model_name: Llama-3.1-8B-Instruct
     endpoint: dynamo.Processor.chat/completions
     port: 8000

   Processor:
     common-configs: [model, block-size, max-model-len, router]

   Router:
     min-workers: 1
     common-configs: [model]

   VllmWorker:
     max-num-batched-tokens: 16384
     remote-prefill: true
     conditional-disagg: true
     tensor-parallel-size: 1
     enable-prefix-caching: true
     max-prefill-queue-size: 5
     ServiceArgs:
       workers: 1
       resources:
         gpu: 1
     common-configs: [model, block-size, max-model-len, router, kv-transfer-config]

   PrefillWorker:
     max-num-batched-tokens: 16384
     ServiceArgs:
       workers: 1
       resources:
         gpu: 1
     common-configs: [model, block-size, max-model-len, kv-transfer-config]
   ```

4. **Start the Service on Node A**

   ```bash
   cd /workspace/dynamo/examples/llm
   dynamo serve graphs.agg_router:Frontend -f ./configs/multinode_pd.yaml
   ```

5. **Set Environment Variables on Node B**

   ```bash
   export ETCD_ENDPOINTS=http://x:2379
   export NATS_SERVER=nats://x:4222
   ```

6. **Launch PrefillWorker on Node B**

   ```bash
   dynamo serve components.prefill_worker:PrefillWorker -f ./configs/multinode_pd.yaml
   ```

> This setup works when A and B have heterogeneous chips.
