### ISSUE TITLE
Remote Prefill Crash with disagg_router.yaml

### ISSUE THREAD

**Issue by mjp9527** [ai-dynamo/dynamo#419]
Great job! I encountered a problem with remote-prefill, disagg_router.yaml is
```
Frontend:
  served_model_name: qwq-32B
  endpoint: dynamo.Processor.chat/completions
  port: 8000

Processor:
  model: qwq
  block-size: 64
  max-model-len: 16384
  router: kv

Router:
  model-name: qwq
  min-workers: 1

VllmWorker:
  model: qwq
  kv-transfer-config: '{"kv_connector":"DynamoNixlConnector"}'
  block-size: 64
  max-model-len: 16384
  max-num-batched-tokens: 16384
  remote-prefill: true
  conditional-disagg: true
  max-local-prefill-length: 50
  max-prefill-queue-size: 50
  tensor-parallel-size: 1
  router: kv
  enable-prefix-caching: false
  ServiceArgs:
    workers: 3
    resources:
      gpu: 1

PrefillWorker:
  model:qwq
  kv-transfer-config: '{"kv_connector":"DynamoNixlConnector"}'
  block-size: 64
  max-model-len: 16384
  max-num-batched-tokens: 16384
  tensor-parallel-size: 1
  ServiceArgs:
    workers: 1
    resources:
      gpu: 1
```

```
backtrace (tid:  59888)
 0  /mnt/disk1/mjp/dynamo/venv/lib/python3.12/site-packages/nixl/../.nixl.mesonpy.libs/./../nixl.libs/libucs-36b9ef61.so.0.0.0(ucs_handle_error+0x304) [0x7ff41b1ad074]
 1  /mnt/disk1/mjp/dynamo/venv/lib/python3.12/site-packages/nixl/../.nixl.mesonpy.libs/./../nixl.libs/libucs-36b9ef61.so.0.0.0(+0x3c274) [0x7ff41b1ad274]
 2  /mnt/disk1/mjp/dynamo/venv/lib/python3.12/site-packages/nixl/../.nixl.mesonpy.libs/./../nixl.libs/libucs-36b9ef61.so.0.0.0(+0x3c4b8) [0x7ff41b1ad4b8]
 3  /usr/lib/x86_64-linux-gnu/libc.so.6(+0x45320) [0x7ff58e6c3320]
 4  /usr/lib/x86_64-linux-gnu/libc.so.6(+0x1a12cd) [0x7ff58e81f2cd]
 5  /mnt/disk1/mjp/dynamo/venv/lib/python3.12/site-packages/nixl/../.nixl.mesonpy.libs/./../nixl.libs/libucp-595be55f.so.0.0.0(+0x9140f) [0x7ff41b28a40f]
 6  /mnt/disk1/mjp/dynamo/venv/lib/python3.12/site-packages/nixl/../.nixl.mesonpy.libs/./../nixl.libs/libuct-4eacacdc.so.0.0.0(uct_tcp_ep_am_bcopy+0x8d) [0x7ff41b14657d]
 7  /mnt/disk1/mjp/dynamo/venv/lib/python3.12/site-packages/nixl/../.nixl.mesonpy.libs/./../nixl.libs/libucp-595be55f.so.0.0.0(+0x916e6) [0x7ff41b28a6e6]
 8  /mnt/disk1/mjp/dynamo/venv/lib/python3.12/site-packages/nixl/../.nixl.mesonpy.libs/./../nixl.libs/libucp-595be55f.so.0.0.0(ucp_wireup_replay_pending_requests+0xd5) [0x7ff41b312a15]
 9  /mnt/disk1/mjp/dynamo/venv/lib/python3.12/site-packages/nixl/../.nixl.mesonpy.libs/./../nixl.libs/libucp-595be55f.so.0.0.0(ucp_wireup_eps_progress+0x460) [0x7ff41b312fb0]
10  /mnt/disk1/mjp/dynamo/venv/lib/python3.12/site-packages/nixl/../.nixl.mesonpy.libs/./../nixl.libs/libucs-36b9ef61.so.0.0.0(+0x2bab0) [0x7ff41b19cab0]
11  /mnt/disk1/mjp/dynamo/venv/lib/python3.12/site-packages/nixl/../.nixl.mesonpy.libs/./../nixl.libs/libucp-595be55f.so.0.0.0(ucp_worker_progress+0x7a) [0x7ff41b261b7a]
12  /mnt/disk1/mjp/dynamo/venv/lib/python3.12/site-packages/nixl/../.nixl.mesonpy.libs/libnixl.so(_ZN13nixlUcxEngine12progressFuncEv+0x4c) [0x7ff41b3be7bc]
13  /usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0xeabb4) [0x7ff58a336bb4]
14  /usr/lib/x86_64-linux-gnu/libc.so.6(+0x9ca94) [0x7ff58e71aa94]
15  /usr/lib/x86_64-linux-gnu/libc.so.6(__clone+0x44) [0x7ff58e7a7a34]
```
