### ISSUE TITLE
dynamo serve disagg_router hang at RemotePrefillParams

### ISSUE THREAD

**Issue by gongwei-130** [ai-dynamo/dynamo#432]
I build docker image and run in the container, agg works fine, but if launch with disagg_router, the prefill worker would hang at generating 

<img width="1504" alt="Image" src="https://github.com/user-attachments/assets/2142da78-c507-4d35-aea6-d3ce35d14286" />

, https://github.com/ai-dynamo/dynamo/blob/main/examples/llm/components/prefill_worker.py#L120.

command: `dynamo serve graphs.disagg_router:Frontend -f configs/disagg_router.yaml`
disagg_router.yaml:

```
Frontend:
  served_model_name: deepseek-ai/DeepSeek-R1-Distill-Llama-8B
  endpoint: dynamo.Processor.chat/completions
  port: 8000

Processor:
  model: deepseek-ai/DeepSeek-R1-Distill-Llama-8B
  block-size: 64
  max-model-len: 16384
  router: kv

Router:
  model-name: deepseek-ai/DeepSeek-R1-Distill-Llama-8B
  min-workers: 1

VllmWorker:
  model: deepseek-ai/DeepSeek-R1-Distill-Llama-8B
  kv-transfer-config: '{"kv_connector":"DynamoNixlConnector"}'
  block-size: 64
  max-model-len: 16384
  max-num-batched-tokens: 16384
  remote-prefill: true
  conditional-disagg: true
  max-local-prefill-length: 10
  max-prefill-queue-size: 2
  tensor-parallel-size: 1
  router: kv
  enable-prefix-caching: true
  ServiceArgs:
    workers: 1
    resources:
      gpu: 1

# TODO - set all of these but model as default
PrefillWorker:
  model: deepseek-ai/DeepSeek-R1-Distill-Llama-8B
  kv-transfer-config: '{"kv_connector":"DynamoNixlConnector"}'
  block-size: 64
  max-model-len: 16384
  max-num-batched-tokens: 16384
  ServiceArgs:
    workers: 1
    resources:
      gpu: 1
```
