### ISSUE TITLE
About ‘disagg_router’,  All traffic enters VllmWorker, does PrefillWorker have no traffic?

### ISSUE THREAD

**Issue by skyCreateXian** [ai-dynamo/dynamo#462]
INPUT_LEN=200
OUTPUT_LEN=10

config:
```
Frontend:
  served_model_name: qwen2-7B
  endpoint: dynamo.Processor.chat/completions
  port: 8000
  ServiceArgs:
    workers: 1

Processor:
  model: /workspace/Qwen2-7B-Instruct/
  block-size: 64
  max-model-len: 16384
  router: kv
  ServiceArgs:
    workers: 1

Router:
  model-name: /workspace/Qwen2-7B-Instruct/
  min-workers: 1

VllmWorker:
  model: /workspace/Qwen2-7B-Instruct/
  enforce-eager: false
  kv-transfer-config: '{"kv_connector":"DynamoNixlConnector"}'
  block-size: 64
  max-model-len: 16384
  max-num-batched-tokens: 16384
  conditional-disagg: true
  max-local-prefill-length: 10
  max-prefill-queue-size: 1000
  tensor-parallel-size: 1
  router: kv
  enable-prefix-caching: true
  ServiceArgs:
    workers: 1
    resources:
      gpu: 1

# TODO - set all of these but model as default
PrefillWorker:
  model: /workspace/Qwen2-7B-Instruct/
  enforce-eager: false
  kv-transfer-config: '{"kv_connector":"DynamoNixlConnector"}'
  block-size: 64
  max-model-len: 16384
  max-num-batched-tokens: 16384
  ServiceArgs:
    workers: 3
    resources:
      gpu: 1

```
PrefillWorker GPU utilization rate is 0 ？
