### ISSUE TITLE
[BUG]: Severe Load Imbalance in TensorRT-LLM KV Aware Routing with Shared System Prompts

### ISSUE THREAD

**Issue by Nekofish-L** [ai-dynamo/dynamo#737]
### Describe the Bug

During stress testing using a dataset containing shared system prompts, we observe that TensorRT-LLM routing directs all requests to a single instance despite having 8 instances configured. This results in severe load imbalance, with one instance overloaded while others remain idle.

### Steps to Reproduce

1. Configure 8 instances with KV-aware routing
2. Send a request containing the shared system prompt prefix
3. Execute stress test using dataset with common system prompt prefix and variable user prompts
4. Observe request distribution via monitoring tools

### Expected Behavior

The router should:

- Maintain KV-aware efficiency for dynamic request routing
- Enforce load distribution when identical prompts are detected
- Maximize hardware utilization across all available instances

### Actual Behavior

KV aware router directs all requests to a single instance despite having 8 instances configured.

![Image](https://github.com/user-attachments/assets/bbf95bf3-72ee-4f6a-8474-1b16f026fa54)

### Environment

OS: Ubuntu 24.04
ai-dynamo: v0.1.1 (from source with tag v0.1.1)
ai-dynamo-rt: v0.1.1 (from source with tag v0.1.1)
trtllm commit: 0d4d50a745 (follow ./container/build_trtllm_base_image.sh)
CPU arch: x86_64
CUDA verison: 12.8
GPU arch: NVIDIA H20
Python version: 3.12.3
glibc version: 2.39
docker version: 26.1.3

### Additional Context

Is this the expected behavior for KV aware routing? If I want to introduce load-balancing constraints in the router, what would be the recommended approach?

**Comment by Nekofish-L** [comment]
**My configuration:**

- model: Qwen2.5-32B FP8

`configs/agg_router.yaml`
```
Frontend:
  served_model_name: Qwen2.5-32B-Instruct-FP8-Dynamic-modelopt
  endpoint: dynamo.Processor.chat/completions
  port: 8124

Processor:
  engine_args: "configs/llm_api_config_router.yaml"
  router: kv

Router:
  model-name: "/models/Qwen2.5-32B-Instruct-FP8-Dynamic-modelopt"
  min-workers: 8

TensorRTLLMWorker:
  engine_args: "configs/llm_api_config_router.yaml"
  router: kv
  ServiceArgs:
    workers: 8
    resources:
      gpu: 1
```

`configs/llm_api_config_router.yaml`
```
model_name: "/models/Qwen2.5-32B-Instruct-FP8-Dynamic-modelopt"
model_path: null
tensor_parallel_size: 1
moe_expert_parallel_size: 1
enable_attention_dp: false
max_num_tokens: 8192
max_batch_size: 256
trust_remote_code: true
backend: pytorch
enable_chunked_prefill: true

kv_cache_config:
  free_gpu_memory_fraction: 0.95

pytorch_backend_config:
  enable_overlap_scheduler: true
  use_cuda_graph: true
```
