### ISSUE TITLE
[BUG]: Significant perf degradation in disagg depending on how workspace is mounted

### ISSUE THREAD

**Issue by tedzhouhk** [ai-dynamo/dynamo#875]
### Describe the Bug

Start a 1P1D disagg service with different workspace mounting mechanism, dump 50 i3000o150 request and observe the throughput:

- do no mount anything and start from the copied `/workspace/` when the docker image is built: 37.87
- use `--mount-workspace` and mount the repo to `/workspace`: 102.81
- use `-v <PATH_TO_DYNAMO_REPO>:/dynamo`: 38.07

### Steps to Reproduce

Build & run docker:
```
./container/build.sh
method 1: ./container/run.sh -it
method 2: ./container/run.sh -it --mount-workspace
method 3: ./container/run.sh -it -v <PATH_TO_DYNAMO_REPO>:/dynamo
```

Start a 1P1D server with the following config in the corresponding `examples/llm` folder:
```
Common:
  model: deepseek-ai/DeepSeek-R1-Distill-Llama-8B
  block-size: 64
  max-model-len: 16384
  kv-transfer-config: '{"kv_connector":"DynamoNixlConnector"}'

Frontend:
  served_model_name: deepseek-ai/DeepSeek-R1-Distill-Llama-8B
  endpoint: dynamo.Processor.chat/completions
  port: 8000

Processor:
  router: round-robin
  common-configs: [model, block-size]

VllmWorker:
  remote-prefill: true
  conditional-disagg: false
  ServiceArgs:
    workers: 1
    resources:
      gpu: 1
  common-configs: [model, block-size, max-model-len, kv-transfer-config]

PrefillWorker:
  max-num-batched-tokens: 16384
  ServiceArgs:
    workers: 1
    resources:
      gpu: 1
  common-configs: [model, block-size, max-model-len, kv-transfer-config]
```

Run GAP
```
genai-perf profile \
    --model deepseek-ai/DeepSeek-R1-Distill-Llama-8B \
    --tokenizer deepseek-ai/DeepSeek-R1-Distill-Llama-8B \
    --service-kind openai \
    --endpoint-type chat \
    --endpoint /v1/chat/completions \
    --streaming \
    --url http://localhost:8000/ \
    --synthetic-input-tokens-mean 3000 \
    --synthetic-input-tokens-stddev 0 \
    --output-tokens-mean 150 \
    --output-tokens-stddev 0 \
    --extra-inputs max_tokens:150 \
    --extra-inputs min_tokens:150 \
    --extra-inputs ignore_eos:true \
    --concurrency 50 \
    --request-count 50 \
    --warmup-request-count 2 \
    --num-dataset-entries 1000 \
    --random-seed 100 \
    -- \
    -v \
    --max-threads 50
```

### Expected Behavior

All 3 path to start dynamo from achieve >=350tok/s (this is perf of TP1 aggregated server).

### Actual Behavior

>50% slower

### Environment

root@ubuntu:/workspace/examples/llm# dynamo env
System Information:
OS: Ubuntu 24.04
Glibc Version: 2.39
GCC Version: 13.3.0
Cmake Version: 3.28.3
Rust Version: 1.86.0
Docker Version: N/A

CPU Information:
Architecture:                         x86_64
CPU op-mode(s):                       32-bit, 64-bit
Address sizes:                        46 bits physical, 57 bits virtual
Byte Order:                           Little Endian
CPU(s):                               32
On-line CPU(s) list:                  0-31
Vendor ID:                            AuthenticAMD
Model name:                           AMD EPYC 9254 24-Core Processor
BIOS Model name:                        CPU @ 0.0GHz
BIOS CPU family:                      0
CPU family:                           25
Model:                                17
Thread(s) per core:                   2
Core(s) per socket:                   4
Socket(s):                            4
Stepping:                             1
BogoMIPS:                             5799.99
Flags:                                fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid tsc_known_freq pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm cmp_legacy svm cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw topoext perfctr_core invpcid_single ssbd ibrs ibpb stibp vmmcall fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid avx512f avx512dq rdseed adx smap avx512ifma clflushopt clwb avx512cd sha_ni avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves avx512_bf16 clzero xsaveerptr wbnoinvd arat npt lbrv nrip_save tsc_scale vmcb_clean v_vmsave_vmload avx512vbmi umip pku ospke avx512_vbmi2 gfni vaes vpclmulqdq avx512_vnni avx512_bitalg avx512_vpopcntdq la57 rdpid fsrm arch_capabilities
Virtualization:                       AMD-V
Hypervisor vendor:                    KVM
Virtualization type:                  full
L1d cache:                            512 KiB (16 instances)
L1i cache:                            512 KiB (16 instances)
L2 cache:                             16 MiB (16 instances)
L3 cache:                             64 MiB (2 instances)
NUMA node(s):                         1
NUMA node0 CPU(s):                    0-31
Vulnerability Gather data sampling:   Not affected
Vulnerability Itlb multihit:          Not affected
Vulnerability L1tf:                   Not affected
Vulnerability Mds:                    Not affected
Vulnerability Meltdown:               Not affected
Vulnerability Mmio stale data:        Not affected
Vulnerability Reg file data sampling: Not affected
Vulnerability Retbleed:               Not affected
Vulnerability Spec rstack overflow:   Mitigation; safe RET, no microcode
Vulnerability Spec store bypass:      Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:             Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:             Mitigation; Retpolines; IBPB conditional; IBRS_FW; STIBP always-on; RSB filling; PBRSB-eIBRS Not affected; BHI Not affected
Vulnerability Srbds:                  Not affected
Vulnerability Tsx async abort:        Not affected

Python Version: 3.12.3
Python Platform: Linux-5.15.0-116-generic-x86_64-with-glibc2.39

Python Packages:
ai-dynamo: 0.2.0
ai-dynamo-runtime: 0.2.0
ai-dynamo-vllm: 0.8.4
genai-perf: 0.0.12
nixl: Not installed
numpy: 1.26.4
nvidia-cublas-cu12: 12.4.5.8
nvidia-cuda-cupti-cu12: 12.4.127
nvidia-cuda-nvrtc-cu12: 12.4.127
nvidia-cuda-runtime-cu12: 12.4.127
nvidia-cudnn-cu12: 9.1.0.70
nvidia-cufft-cu12: 11.2.1.3
nvidia-curand-cu12: 10.3.5.147
nvidia-cusolver-cu12: 11.6.1.9
nvidia-cusparse-cu12: 12.3.1.170
nvidia-ml-py: 12.570.86
nvidia-nccl-cu12: 2.21.5
nvidia-nvjitlink-cu12: 12.4.127
nvidia-nvtx-cu12: 12.4.127
pyzmq: 26.4.0
tensorrt_llm: Not installed
torch: 2.6.0
torchaudio: 2.6.0
transformers: 4.51.3
tritonclient: Not installed
