### ISSUE TITLE
[FEATURE]: How to test the functionality of DynamoNcclConnector？

### ISSUE THREAD

**Issue by Sakurafwsv** [ai-dynamo/dynamo#883]
### Feature request

In the dynamo patch for vllm, two functions, DynamoNixlConnector and DynamoNcclConnector, have been added. How can we test the functionality of DynamoNcclConnector？

### Describe the problem you're encountering

Now I conduct the test based on the README.md under the “dynamo/examples/llm” path and modify the file “./configs/disagg_router.yaml”. The kv-transfer-config parameter is set to '{"kv_connector":"DynamoNcclConnector", "kv_role": "kv_both"}'. But when running the command "dynamo serve graphs.disagg_router:Frontend -f./configs/disagg_router.yaml", an error occurred, showing the NixlMetadata as the None value. I checked the relevant code, it seems that the code in "dynamo/examples/LLM/components" is written specifically to Nixl test? If I want to use the DynamoNcclConnector, how should I test it? Are there any relevant examples?

### Describe alternatives you've tried

None

**Comment by Mr8** [comment]
same error, does there need other config values of kv-transfer-config ?
```
serve_dynamo.py: error: argument --kv-transfer-config: invalid from_cli value: '{"kv_connector":"DynamoNcclConnector"}'
```

configuration:
```
Common:
  model: neuralmagic/DeepSeek-R1-Distill-Llama-70B-FP8-dynamic
  #kv-transfer-config: '{"kv_connector":"DynamoNixlConnector"}'
  kv-transfer-config: '{"kv_connector":"DynamoNcclConnector"}'
  #router: kv
  # Number of tokens in a batch for more efficient chunked transfers to GPUs.
  block-size: 128
  max-model-len: 3500
  max-num-batched-tokens: 3500
  disable-log-requests: true

Frontend:
  # This model was chosen for its 70B size and FP8 precision, which the TP and
  # DP configurations were tuned for its size, and its precision reduces model
  # and KV cache memory usage and easing remote cache transfer.
  served_model_name: neuralmagic/DeepSeek-R1-Distill-Llama-70B-FP8-dynamic
  endpoint: dynamo.Processor.chat/completions
  port: 8000

Processor:
  common-configs: [model, router]

# x1 process with 4 GPUs generating output tokens (the "decode" phase).
VllmWorker:
  common-configs: [model, kv-transfer-config, router, block-size, max-model-len, disable-log-requests]
  # Enable prefill at different workers.
  remote-prefill: true
  conditional-disagg: false
  max-prefill-queue-size: 4
  gpu-memory-utilization: 0.95
  tensor-parallel-size: 4
  ServiceArgs:
    workers: 1
    resources:
      gpu: 4

# x4 processes each with 1 GPU handling the initial prefill (context embedding) phase.
PrefillWorker:
  common-configs: [model, kv-transfer-config, block-size, max-model-len, max-num-batched-tokens, gpu-memory-utilization, disable-log-requests]
  tensor-parallel-size: 1
  ServiceArgs:
    workers: 4
    resources:
      gpu: 1
```
